### ISSUE TITLE
[Question] Any examples of how to do normal mapping?

### ISSUE THREAD

**Issue by lokimeyburg** [mellinoe/veldrid#103]
I've really been enjoying using Veldrid and I'm at the point where I'm looking to implement normal mapping. Do you have any examples you could point me to? Or maybe just a brief explanation about how you might go about implementing normal mapping with Veldrid?

**Comment by mellinoe** [comment]
Hey @lokimeyburg , there's no example code for this yet, but it would be great to get something added to the samples repository. Implementing normal mapping in Veldrid will be about the same as any other graphics library, and you should be able to follow along with, for example, [this OpenGL tutorial](http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-13-normal-mapping/). Obviously, the OpenGL-specific stuff needs to be translated, but it shouldn't be that difficult. The [Textured Cube example](https://github.com/mellinoe/veldrid-samples/blob/master/src/TexturedCube/Application/TexturedCube.cs#L49) could be a good starting point for a new sample project, since it already handles most everything you would need.

There's a few main things to handle:

* Calculate normals/tangents/bitangents and passing them as vertex attributes, along with the existing position/UV attributes. If you're rendering a cube, then computing the normals/tangents/bitangents is pretty trivial. Assimp can compute these values automatically for you if you're using it to load arbitrary models.

The TexturedCube example just uses two vertex attributes: https://github.com/mellinoe/veldrid-samples/blob/master/src/TexturedCube/Application/TexturedCube.cs#L49. You could simply add three extra attributes and make sure they are uploaded into the vertex buffer. E.g.:

```C#
new VertexLayoutDescription(
    new VertexElementDescription("Position", VertexElementSemantic.Position, VertexElementFormat.Float3),
    new VertexElementDescription("TexCoords", VertexElementSemantic.TextureCoordinate, VertexElementFormat.Float2),
    new VertexElementDescription("Normal", VertexElementSemantic.Normal, VertexElementFormat.Float3),
    new VertexElementDescription("Tangent", VertexElementSemantic.Normal, VertexElementFormat.Float3),
    new VertexElementDescription("Bitangent", VertexElementSemantic.Normal, VertexElementFormat.Float3))
```

* Add the normal map to be sampled in the fragment shader. The color Texture is described [here](https://github.com/mellinoe/veldrid-samples/blob/master/src/TexturedCube/Application/TexturedCube.cs#L70) -- you can just add another TextureView (the normal map) to the layout and then add it to the ResourceSet [here](https://github.com/mellinoe/veldrid-samples/blob/master/src/TexturedCube/Application/TexturedCube.cs#L87).
* Modify the shader code to use the normal map. You'll have to define the new vertex attributes and the new texture, and then do the appropriate stuff with them. You should be able to follow the OpenGL tutorial pretty much directly at this point.

**Comment by lokimeyburg** [comment]
Thanks for the thorough notes, @mellinoe. I was thinking along the same lines. I'll see what I can come up with (and if I do, I'll be sure to create a pull request).
