### ISSUE TITLE
SDL not configured with EGL support

### ISSUE THREAD

**Issue by tzachshabtay** [mellinoe/veldrid#113]
Running NeoDemo on a mac.
When I switch the backend to OpenGL ES demo crashes with:

```
"Unable to create OpenGL Context: \"SDL not configured with EGL support\". This may indicate that the system does not support the requested OpenGL profile, version, or Swapchain format.”
```

So I'm guessing something's wrong with the backend detection here (i.e OpenGL ES should not be enabled in this case)?

**Comment by mellinoe** [comment]
As far as I know, macOS does not support OpenGL ES at all.

> (i.e OpenGL ES should not be enabled in this case)?

Yeah, that's correct. The other options are greyed out because Veldrid does real support checks for those.

Unfortunately, Veldrid doesn't currently detect whether OpenGL or OpenGL ES are "supported" by the system, because it is rather complicated. I can probably do better OS-based checks, though, and at least detect this case.

**Comment by mellinoe** [comment]
Calling `GraphicsDevice.IsBackendSupported(GraphicsBackend.OpenGLES)` on macOS will now return `false`. NeoDemo uses that information to determine whether an option is available in the drop-down.

https://github.com/mellinoe/veldrid/commit/46ce154a0ebdded4fccee7ff93dec4c31352b5d8

**Comment by mellinoe** [comment]
This one should have been improved by the commit above -- please re-open if that's not the case.
