### ISSUE TITLE
[Question]  why CommandList is called in drawing Loop ?

### ISSUE THREAD

**Issue by a348019017** [mellinoe/veldrid#123]
I am confused why CommandList not create and set in advance ,but set in render loop. I see the vulkan C++ code, vkCommandBuffer just created ahead .

**Comment by a348019017** [comment]
Can I set commandList advance like this,I am out of the door so have not test.
private  void preBindingCommandList()
{
     _cl.begin();    
     _cl.SetPipeLineAndOthers();
    _cl.End()
}

private void RenderLoop()
{
while(true)
{
_cl.SetFramebuffer(XXX);
_gd.submit(_cl);
_gd.SwapBuffers(mainswap);
}
}

**Comment by mellinoe** [comment]
No, that sort of thing isn't supported by Veldrid. If I'm reading your code snippet right (and it would need to be written a bit differently to work), you are interested in a couple of features:

1. Re-usable command buffers. Right now, Veldrid's CommandLists are not re-usable, primarily because Metal's are not -- or rather weren't. They can be now with a newer Metal feature (Indirect Command Buffers).

2. "Secondary" command buffers. The ability to record a set of commands and then replay it _inside_ another one. This isn't supported either, and some investigation needs to be done as to its feasibility in all of the backends, as well as the limitations. Metal would likely need Indirect Command Buffers for this to work (if it would at all).

**Comment by a348019017** [comment]
Thank you,It seems ok the way you do.
