### ISSUE TITLE
Immutable resources 

### ISSUE THREAD

**Issue by amerkoleci** [mellinoe/veldrid#13]
Now to update buffers or textures there a Update method on CommandList, all backends can handle immutable data being passed during creation.

**Comment by mellinoe** [comment]
Resource creation is one place that I would like for things to be simpler, and this could be one way to help the common case.

BufferDescription and TextureDescription could be augmented with some kind of `InitialData` structure containing an array of data regions used to initialize the object.

Threading concerns throw a bit of a wrench into the mix, though. I intend for resource creation to be completely free-threaded, meaning you can create and dispose resources from any thread at any time. This is how modern API's work, and it's much cleaner and easier to use. Resource updates are not free-threaded, though -- they have to be issued into a CommandList because they use synchronized mechanisms in the backends. I could defer the actual initial resource update until the resource is first used, which is essentially what the OpenGL backend does to achieve multithreading.

Perhaps the better option is to attempt to make resource updates free-threaded like resource creation is. I'm not sure how exactly that will work, though -- I'd have to think about it. It would improve the API if resource updates could be used at any time.

**Comment by mellinoe** [comment]
I'm not planning on doing anything in this space for the first release. The above change that I mentioned is implemented, though -- all resource updates can be done in a free-threaded manner via the `GraphicsDevice`. Perhaps in the future I will add some convenience methods that create DeviceBuffers and Textures with initial data, but in the meantime it's simple enough to just make a follow-up call to GraphicsDevice.Update____ (or make a custom helper).
