### ISSUE TITLE
SDL2Window.BorderState

### ISSUE THREAD

**Issue by tzachshabtay** [mellinoe/veldrid#131]
Hi, I couldn't find a property in SDL2Window to set the border state.
I expected there to be an enum with 3 states: Resizable, Fixed and Hidden.

I also see that WindowState has both Fullscreen and BorderlessFullscreen -> I understand that borderless fullscreen is a common requirement, but I still think it's wrong.
I'd expect to set WindowState.Fullscreen and BorderState.Hidden to achieve that same effect.

Thanks.

**Comment by mellinoe** [comment]
SDL2 has a distinct "borderless fullscreen" concept which is exposed in the API: https://wiki.libsdl.org/SDL_SetWindowFullscreen (`SDL_WINDOW_FULLSCREEN` vs `SDL_WINDOW_FULLSCREEN_DESKTOP`), which is why the distinction is made in Veldrid's API as well.

I could see exposing the "borderless" and "resizable" flags by themselves, independent of the "fullscreen-ness" of the Window:

https://wiki.libsdl.org/SDL_SetWindowBordered
https://wiki.libsdl.org/SDL_SetWindowResizable

**Comment by mellinoe** [comment]
I've added support for `Sdl2Window.BorderVisible` and `Sdl2Window.Resizable`, which are wrappers around the functionality mentioned above. This should cover the scenario in question. This will be a part of the upcoming 4.5.0 release.
