### ISSUE TITLE
OpenGL - Use of struct array uniforms

### ISSUE THREAD

**Issue by AlzPatz** [mellinoe/veldrid#139]
Hi, I had a question I was trying to answer, from experimentation it seems the answer is perhaps no.

Can an OpenGL shader (in Veldrid) have a uniform that is comprised of a fixed length struct, either naked or within a uniform block?

I have tried:

```
uniform struct example
{
    vec4 Colour;
    vec4 Size;
} ExampleArray[10];
```
with...

`cl.UpdateBuffer(buffer, 0, ref examples[0], 10 * SizeInBytes);
`

(not expecting this version, a 'naked' uniform to work (as is the case in veldrid with opengl for 'standard' uniforms bar samplers)

and also tried wrapping in the uniform block:
```
struct Example
{
    vec4 Color;
    vec4 Size;
};

uniform AUniformBlock
{
   Example[] Examples;
};
```
with...

`cl.UpdateBuffer(_buffer, 0, ref exampleStruct);`

So far I am not getting the uniforms updated with values. Probably again some other user error

Thanks

**Comment by mellinoe** [comment]
You need to use a sized array in the second version, but it should work:

uniform AUniformBlock
{
   Example Examples[10];
};

**Comment by AlzPatz** [comment]
Hi, I had a typo before, I am indeed using an explicitly sized array in both cases. I'll do some more investigation, problem must be elsewhere. thanks!

**Comment by AlzPatz** [comment]
Unfortunately I've had no joy thus far - have tried a few things. I'll keep at it, but I've made an example in any case (note I've made it update the buffer once per frame to try and find some more intel using renderdoc). renderdoc shows the array is all 0's in any case. please don't feel like you need to take a look as this is clearly another basic issue i'm overlooking.

https://github.com/AlzPatz/VeldridFixedSizeArrayInUniformBlock

**Comment by mellinoe** [comment]
Hi @AlzPatz , thanks for providing the sample project. The problem in this case is that you are using `GraphicsDevice.UpdateBuffer<T>(DeviceBuffer, uint, ref T)` with a `T` type that is not  blittable. `ExampleStruct` is fully blittable, but the `UniformBlockStruct` type is not, because it contains a managed array (`ExampleStruct[] ArrayOfExampleStructs`). Conceptually, the UpdateBuffer overload you are using should have an `unmanaged` constraint on `T`. This constraint didn't exist yet when I wrote the library.

There's a couple of fixes, but the easiest is to just replace this: 

```C#
private UniformBlockStruct _data;
```

with this:

```C#
private ExampleStruct[] _data = new ExampleStruct[]
{
    new ExampleStruct()
    {
        V0 = Vector2.One,
        V1 = Vector2.One
    },
    new ExampleStruct()
    {
        V0 = Vector2.One,
        V1 = Vector2.One
    },
    new ExampleStruct()
    {
        V0 = new Vector2(300.0f, 400.0f),
        V1 = new Vector2(100.0f, 200.0f)
    },
    new ExampleStruct()
    {
        V0 = Vector2.One,
        V1 = Vector2.One
    }
};
```

There is a GraphicsDevice.UpdateBuffer overload which just takes an array of a blittable type:
```C#
_device.UpdateBuffer(_uniformBuffer, 0, _data);
```

I can see that the data is correctly getting into the fragment shader with that fix.

**Comment by AlzPatz** [comment]
That makes sense - awesome + thanks again for the help !! :) :+1:
