### ISSUE TITLE
Black quad on metal

### ISSUE THREAD

**Issue by tzachshabtay** [mellinoe/veldrid#172]
Rendering a quad with a texture works fine on OpenGL on mono on mac.
But switching the backend to Metal and the quad is rendered black.

Note that the original textured cube sample does render fine on both OpenGL and mono. The difference, as far as I'm aware, is that I'm loading my png texture with system.drawing and the image uses a different pixel format.

To reproduce:
Run `MonoQuad` from [here](https://github.com/tzachshabtay/veldrid-samples/tree/textured_quad), see the 2 quads being rendered.
Then change the backend to metal [here](https://github.com/tzachshabtay/veldrid-samples/blob/0c3649e6a646cfdb64ff2b80a5eb7c432afff168/src/MonoQuad/VeldridStartupWindow.cs#L56) and see the black quads.

**Comment by mellinoe** [comment]
@tzachshabtay The problem here is that you are specifying a `depth` of 0 in your UpdateTexture call. This means that you've effectively asked to copy an empty region. Even when copying 2D regions, the depth parameter should be 1.

The OpenGL backend is ignoring the `depth` parameter for 1D and 2D copies, which it shouldn't be doing. Fixing that will align the backends, but you'll still need to pass 1 for the depth to get anything to render.

**Comment by tzachshabtay** [comment]
Is there a valid use-case for passing 0?
If not, maybe an exception should be thrown for 0 (and negative numbers).

**Comment by mellinoe** [comment]
There's not really a use-case in the senes that it is effectively a no-op. However, it could be useful if the texture region's dimensions were computed from some other information in your application -- having to special case an empty region just to avoid the exception would be annoying. Logically, there's nothing wrong with asking to update an empty region. Further, all the native API's allow it, so it seems best to just keep the current behavior.
