### ISSUE TITLE
SDL_GamerController Instance Id

### ISSUE THREAD

**Issue by AlzPatz** [mellinoe/veldrid#185]
Hi
Quick query. Have been looking at the Sdl2ControllerTracker.

On start up it loops through the number of joysticks based on the SDL_NumJoysticks. It uses that index to check if the Joystick is a Gamecontroller and then opens the controller using that same index.

In the method description for SDL_GameControllerOpen it mentions that this index is NOT the same as the instanceId that should be used later to identify which controller is firing an event (the .which property of later controller events).

However in your example you compare this .which property to the original index of the controller. I also do not notice a way to get back the actual instanceId of a newly created controller. There only appears to be the function to get back a controller from an instanceId.

Is the method description accurate for SDL_GameControllerOpen? does the actual instanceId need to be exposed somewhere or am i missing something?
hope that makes sense

thanks

EDIT: I might as well ask it here. I couldn't work out why you fire Sdl2Events.ProcessEvents() three times in the NeoDemo loop line 225 ish. I've found i don't seem to need to even call this when I have subscribed already. would appreciate if there is some flushing / issues that require this.

**Comment by mellinoe** [comment]
As far as I can tell, you are right about this, but I'm not an expert on SDL2's controller handling. The "instance ID" of a controller is technically different from the index you use to "open" it, and has to be queried separately using SDL_JoystickInstanceID. That function is already exposed in Veldrid.SDL2, as is SDL_GameControllerGetJoystick, which is needed to get an SDL_Joystick from an SDL_GameController. It turns out that in practice, opening a joystick / game controller with index 0 results in an instance ID of 0, so there's no functional difference on my machine. However, I only have on controller plugged in, and there doesn't seem to be any guarantee in the SDL2 API that this would always be true. So it's definitely more correct to actually query for the iD. Sdl2ControllerTracker has been updated on the master branch to do that.

> EDIT: I might as well ask it here. I couldn't work out why you fire Sdl2Events.ProcessEvents() three times in the NeoDemo loop line 225 ish. I've found i don't seem to need to even call this when I have subscribed already. would appreciate if there is some flushing / issues that require this.

Yeah, that's just a copy/paste error, which I'll fix. However, you do need to call `Sdl2Events.ProcessEvents()` _somewhere_ to pump the SDL2 event loop. Subscribing to the callback by itself doesn't cause the events to be processed automatically -- you still have call the method.

**Comment by AlzPatz** [comment]
Thanks for the response, all makes sense. I didn't notice SDL_JoystickInstanceID, for some reason it isn't in the package I restore. I see it was added to the repo 30th March, so I assume it is in 4.6.1, but perhaps i have to wait for it to feed through or clone master. no doubt something odd my end. thanks again

**Comment by mellinoe** [comment]
Yes unfortunately it was added in the commit after 4.6.1. So it will be included in the next version, but otherwise you can get it from the master branch here (or a prerelease package).

**Comment by AlzPatz** [comment]
sorry to ask, but as i'm unable to use the master branch (some complications on arch linux i think), am keen to use a pre-release package from myget. but i seem to be being dense, i don't see anything later than 4.6.1 on 29th march. pretty sure i'm missing something obvious. thanks
