### ISSUE TITLE
Can't Build NeoDemo & Veldrid.ImGui

### ISSUE THREAD

**Issue by ebergerly** [mellinoe/veldrid#186]
First, thanks much for these amazing resources. I successfully have been learning the Veldrid raytracer, and now I just want to add a simple ImGui UI so I can tweak my scenes in real time. But I've been stuck on how to add ImGui.Net to my Veldrid raytracer for weeks. I'd sure appreciate some help. 

I tried to build both Veldrid.ImGui and NeoDemo, hoping they would help. However, for both I get a number of errors and warnings. The errors all say "SourceRoot.SourceLinUrl is empty:....". And the "\src\" folder they are referencing is filled, not empty. And the warnings say "No way to resolve conflicts between "Veldrid.SDL2..." (see attached screenshot). 

BTW, I did successfully build the ImGui.Net.SampleProgram, but I'm scratching my head trying to figure how to inject the Veldrid raytracer into it. 

In any case if anyone can assist with a simple way to get an ImGui.Net UI inside my raytracer I'd sure appreciate it. Thanks much
![Veldrid](https://user-images.githubusercontent.com/50532834/57576100-7ca0c100-7426-11e9-9657-97e30667b247.PNG)

**Comment by mellinoe** [comment]
Those errors occur when you build the project outside of a git repository. I just updated the NuGet package for SourceLink, so that shouldn't happen anymore.

Have you tried using the NuGet packages that are available? You shouldn't need to build anything from source unless you're trying to make some modifications. Integrating ImGui into a Veldrid app should be straightforward -- what have you tried?

**Comment by ebergerly** [comment]
Wow thanks very much for doing that. I got NeoDemo running now.

As far as integrating ImGui into Veldrid raytracer, I've basically placed the raytracer you developed side-by-side with your ImGui.NET.SampleProgram, and tried to figure out what code to copy/paste from ImGui to Veldrid to add a simple UI. Or maybe I should copy/paste from Veldrid to ImGui....

And I get stumped with stuff like the ImGuiController and MemoryEditor, and also how to handle CreateDeviceResources within Veldrid. So I'm wondering stuff like whether all the CreateDeviceResources is now done via the ImGuiController/CreateDeviceResources, or is it done by Veldrdi. And so on. 

Apologies if I'm overlooking something obvious....

**Comment by mellinoe** [comment]
> ImGuiController and MemoryEditor

Don't worry about those. What you want is the [ImGuiRenderer](https://github.com/mellinoe/veldrid/blob/master/src/Veldrid.ImGui/ImGuiRenderer.cs) class. ImGuiController is just a more-or-less identical copy of it that is included in the ImGui.NET repo as an example of how to build a renderer from scratch. Using `ImGuiRenderer` should be pretty simple:

1. Create one by passing in your `GraphicsDevice` and a few other pieces of info
2. Every frame, call `Update()` on it, passing the elapsed time since last frame, and an `InputSnapshot` (retrieved from your window)
3. Every frame, call `Render()` on a `CommandList`

Here's a complete minimal example: https://gist.github.com/mellinoe/5eca1a109a71566f620a05fcb70e74ca

**Comment by ebergerly** [comment]
Wonderful !! Thanks very very much. I got that minimal example running fine, and saw your ImGuiRenderer class code. Pretty slick, it has all the CreateDeviceResources inside. 

Thanks again. A huge help.

**Comment by mellinoe** [comment]
No problem. Let me know if you hit any issues.
