### ISSUE TITLE
Vulkan backend don't work on Ubuntu 19.04

### ISSUE THREAD

**Issue by aashlykov** [mellinoe/veldrid#189]
On the Ubuntu 19.04 with using Vulkan as preffered backend, application crashes with unhandled exception:
Veldrid.VeldridException: The required instance extension was not available: VK_KHR_xlib_surface

Reason of this error was found at file:
src/Veldrid/Vk/VkGraphicsDevice.cs:465
Property RuntimeInformation.OSDescription returns "Unix 5.0.0.15" for Desktop Ubuntu 19.04, so, program code in the specified place detect OS as Android, and this is wrong.

**Comment by mellinoe** [comment]
@aashlykov Sorry that you ran into that. I pushed a fix to master that should fix this problem -- are you able to test that?

**Comment by aashlykov** [comment]
@mellinoe maybe you rushed with this fix? It seems you are using .NET Core for development, but I use the Mono implementation of .NET. Maybe this is reason of different behavior of RuntimeInformation.OSDescription ?
> are you able to test that?
At now - no, I'm not able. When I tried to build Veldrid from sources, there was a lot of problems. This bug I found by using binary packages from Nuget. But if you will describe your development environment in details, I will do everything as you do. I will build and test.
Or, maybe you can build last master, and send me binary files (Veldrid.dll and others) by email?

**Comment by mellinoe** [comment]
> @mellinoe maybe you rushed with this fix? It seems you are using .NET Core for development, but I use the Mono implementation of .NET. Maybe this is reason of different behavior of RuntimeInformation.OSDescription ?

That might have something to do with it. In general, using `OSDescription` to determine runtime behaviour was a bad idea in the first place, because there's no strict rules for what gets returned. It's just supposed to be an informational string. On top of that, VkGraphicsDevice already checks if the surface extensions are available before enabling them, which functions as an OS check by itself. I am considering simplifying the entire block there and just enabling any surface extensions that are available -- the cost of doing that is negligible and it would potentially eliminate more edge cases like this.

> At now - no, I'm not able. When I tried to build Veldrid from sources, there was a lot of problems.

Hm, you shouldn't hit any problems, but I haven't used Ubuntu 19.04 myself. Are you hitting issues related to Libgit2sharp? I had hoped those issues were fixed, since they've been a recurring problem in the past.

In the meantime, can you try the NuGet package(s) from MyGet? They have the latest version (non-stable) from the master branch:

https://www.myget.org/feed/mellinoe/package/nuget/Veldrid/4.7.0-g66ca7b6e8f

**Comment by aashlykov** [comment]
@mellinoe 
> Are you hitting issues related to Libgit2sharp?

Yes, there are a lot of errors with Libgit2sharp.

> In the meantime, can you try the NuGet package(s) from MyGet?

Ok, I will test packages from this place. Today, but some time later.
OFFTOP: reading the library source code, I noticed that:
1. Library use SDL2 for windows management
2. Library use Vulkan as one of backends
But library don't use this SDL2 function: https://wiki.libsdl.org/SDL_Vulkan_CreateSurface?highlight=%28%5CbCategoryVulkan%5Cb%29%7C%28CategoryEnum%29%7C%28CategoryStruct%29
but this function seems to be useful for library. Maybe this information will be useful for you in future. Or not)))

**Comment by mellinoe** [comment]
> Library use SDL2 for windows management

SDL2 integration is actually just a convenience layer on top of the core Veldrid library, which can be used with any windowing library. The [article on Swapchains](https://veldrid.dev/articles/swapchains.html#creating-swapchains) may provide a bit more insight into how this works exactly. The Veldrid.SDL2 library has a method that is a kind of analog to `SDL_Vulkan_CreateSurface`: [VeldridStartup.GetSwapchainSource](https://github.com/mellinoe/veldrid/blob/729ae642f0e5920a0f6b1586c421a0ed2f8ae87f/src/Veldrid.StartupUtilities/VeldridStartup.cs#L139).

> Yes, there are a lot of errors with Libgit2sharp.

I'll pull out my Ubuntu laptop (18.04, but maybe it will repro the issue) and try to fix this, or at least make it so that it can be ignored.

**Comment by mellinoe** [comment]
Hm. It still builds successfully on my Ubuntu 18.04 machine, but not if I upgrade the GitVersioning and SourceLink packages (both of which use libgit2sharp). I'm hesitant to disable them by default on Linux (although I could do that), because the assembly versioning will be incorrect. I'll need to spend some additional time figuring that out.

**Comment by aashlykov** [comment]
Now Vulkan backend works fine. Thanks for so fast fix.
