### ISSUE TITLE
Catching VeldridException resulting from a shader compile error

### ISSUE THREAD

**Issue by danielscherzer** [mellinoe/veldrid#202]
hi and thanks for your very nice graphics library! I'm using the nuget package version 4.6.1

my problem: I need to compile user provided shader code (glsl) during runtime (similar to the editor at https://www.shadertoy.com/new). This works beautifully with your lib by the way. But if the provided shader code has some errors a VeldridException is thrown. Because I need to work on the OpenGL backend (at least for now) this exception is thrown on the Veldrid OpenGL worker thread and not during the call to `CreateShader`, but at a later time, which makes it difficult to catch (without halting the application). Do you have any suggestions how to handle invalid shader code without stopping Veldrid?

**Comment by mellinoe** [comment]
@danielscherzer Thanks for reporting this. I'd definitely like to support this better, and in general I'd like to make the fact that OpenGL stuff happens in a background thread as invisible as possible. In this case, it seems reasonable to synchronize with the execution thread in order to propagate any compiler errors at the time the Shader itself is constructed. Similarly, I think it makes sense to do the same for Pipeline objects, which can fail if the Shaders that you give to it are incompatible (e.g. they use different types for the same uniform variable).

I pushed a change to master that causes the Exceptions to be thrown from `ResourceFactory.CreateShader` and `CreatePipeline`. There should be a pre-release build popping out onto myget sometime soon that you can test if you'd like.

**Comment by danielscherzer** [comment]
Thanks for the quick fix! I installed `4.7.0-g4d09d452ed` and it seems to work exactly like it should. The exception is thrown were it is expected and when I catch it the application still works. Excellent!

One minor thing which is just a cosmetic concern: The `VeldridException` returns the shader log as part of the `VeldridException.Message="Unable to compile shader code for shader [] of type <ShaderType>: ..."`. This makes it possible for app code to parse the shader log for the individual errors, but parsing code could fail in the future if you ever decide to change the syntax of this message. My suggestion would be to put the shader log (additionally) into an inner exception to avoid this.

Thanks again for your great work!
