### ISSUE TITLE
Multiple ImGuiRenderer instances

### ISSUE THREAD

**Issue by ItsNovaHere** [mellinoe/veldrid#274]
Hello, I am trying to render 2 different instances of ImGui (one in the main window, another to an offscreen buffer), however I'm running into issues trying to get both to render and handle input.

Right now I can get either one to render and handle input, while the other doesn't render at all, or both render, with neither receiving input.

Just wonder if this is an error on my part or not.

[Quick code chunk from render loop](https://gist.github.com/ItsNovaHere/8a748d2d7e62b92137e74ec9ed9a7d73)

**Comment by mellinoe** [comment]
You are likely going to need to create and manage two context objects yourself (`ImGui.CreateContext`), and switch between them at the appropriate time (`ImGui.SetCurrentContext`). I have done this in a private game engine where the editor's UI was driven by ImGui, but an embedded game view could also display ImGui widgets and receive localized input. If this is close to what you're doing, then you will need two contexts.

Doing this is a bit tricky, because ImGuiRenderer is not very context-aware. The trick is that you can create a context yourself (ImGui.CreateContext()), make it current (ImGui.SetCurrentContext()), and then construct an ImGuiRenderer as normal. The renderer will use the current context implicitly. Without a context, it normally just creates one automatically. Once you've created two contexts and renderers yourself, you can switch between them, passing the appropriate "input snapshots" to each of them, and issuing relevant draw commands into each. Your loop is roughly correct, but you need to add extra handling for setting up and managing two contexts.

**Comment by ItsNovaHere** [comment]
Alright that appears to work, thank you very much for the help and this library!
