### ISSUE TITLE
Embedding veldrid windows inside ImGUINet

### ISSUE THREAD

**Issue by enquel** [mellinoe/veldrid#290]
Hi!,

I was wondering if and how it would be possible to embed the SampleApplication inside an ImGuiNET window. So basically I have 1 veldrid window with 1 graphics device that renders ImGUINET and 2nd set for the sample application. Now, I imagine for that SampleApplication I would need to modify a startup window to be "virtual"/not rendered (is that possible?) + output description changed so that it renders to a buffer being a textures. Is that the way to go?

**Comment by mellinoe** [comment]
Yes, this is definitely possible, if I understand what you're describing. You basically want the contents of the example projects to be rendered into an ImGui image or button. This is pretty straightforward and is the same process for any kind of "off-screen" rendering. Instead of rendering to the main Swapchain's Framebuffer, you would instead:

1. Create a new Texture, of whatever size you want the ImGui image to appear at.
2. Create a new Framebuffer, which targets the Texture from 1.
3. Before rendering your scene, bind the Framebuffer from 2.
4. Render as normal
5. Pass the Texture from 1. into `ImGuiRenderer.GetOrCreateImGuiBinding`, which gives you an IntPtr.
6. Pass the IntPtr from 6. into ImGui.Image or ImGui.ImageButton.
