### ISSUE TITLE
{Request}add opengl 4.5 support

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [mellinoe/veldrid#295]
Projects like ryujinx need 4.4 mins could that be added ? 
Opentk isnt very good and causes a ton of issues

**Comment by mellinoe** [comment]
What features in OpenGL 4.4 does Ryujinx need that aren't supported by Veldrid's abstraction? Veldrid's _minimum_ supported version is OpenGL 3, but some newer features (e.g. [compute shaders](https://veldrid.dev/api/Veldrid.GraphicsDeviceFeatures.html#Veldrid_GraphicsDeviceFeatures_ComputeShader) from OpenGL 4.3) are still supported, you just need to do runtime feature checks to determine if they are available.

I can't say for certain about Ryujinx's particular codebase (I'm not familiar with it except in passing), but it shouldn't be blocked from using Veldrid because of any particular OpenGL version.

**Comment by mellinoe** [comment]
Closing this out, because I don't believe there's anything to do.
