### ISSUE TITLE
How do I enable VkPhysicalDeviceFeatures::shaderFloat64?

### ISSUE THREAD

**Issue by TJYSunset** [mellinoe/veldrid#296]
An exception was thrown when creating a graphics pipeline with its vertex shader using `dvec2`:
```
Unhandled exception. Veldrid.VeldridException: A Vulkan validation error was encountered: [ErrorEXT] (UnknownEXT)  [ UNASSIGNED-CoreValidation-Shader-FeatureNotEnabled ] Object: VK_NULL_HANDLE (Type = 0) | Shader requires VkPhysicalDeviceFeature
s::shaderFloat64 but is not enabled on the device
```
I do not fully understand what that means, but physical device features seem [hard](https://github.com/mellinoe/veldrid/blob/33e5158046c708b50662fc8fda4a1f896d76a886/src/Veldrid/Vk/VkGraphicsDevice.cs#L668) [coded](https://github.com/mellinoe/veldrid/blob/33e5158046c708b50662fc8fda4a1f896d76a886/src/Veldrid/Vk/VkGraphicsDevice.cs#L742) in `VkGraphicsDevice`'s constructor. Is there a way I can enable more features?

**Comment by mellinoe** [comment]
Unfortunately, there is no extension point for which optional device features are enabled. I have been operating under the belief that it's better to simply enable the optional features when they are available, because the cost has not been very significant to doing so. I would accept a PR that enabled this when available, similar to how other optional features are flipped on in the code.
