### ISSUE TITLE
UpdateBuffer doesn't upload ImmutableArray<T> correctly with Vulkan backend

### ISSUE THREAD

**Issue by TJYSunset** [mellinoe/veldrid#297]
What the title said... I have an `ImmutableArray<A> data` where `A` is a well-defined struct, and I called `graphicsDevice.UpdateBuffer(buffer, 0, data)` to upload data to GPU. When inspecting with RenderDoc I found my SSBO only had its first element updated (with an incorrect value) and the rest were all zeros. If I call `graphicsDevice.UpdateBuffer(buffer, 0, data.ToArray())` instead, the SSBO's content is correct.

**Comment by mellinoe** [comment]
This is likely a peculiarity caused by the fact that `ImmutableArray` is actually a structure, and the UpdateBuffer function assumes that, if you give it a structure, it represents a blittable value type that it can copy directly. The second version works correctly because you are turning it into an array, which uses a different overload that correctly handles copying the entire sequence of data.

It's been a while since I've used System.Collections.Immutable, but for this to work without copying the data, you would need to be able to access the ImmutableArray's underlying array, and pass that to the UpdateBuffer function. Either that, or get access to a pinnable reference that you could use. It seems like [that might be available](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1.asspan?view=netcore-3.1) in .NET 5, but I don't see anything available now that you could use.
