### ISSUE TITLE
nU get packge

### ISSUE THREAD

**Issue by nictaylr** [mellinoe/veldrid#3]
do you plan: release nu get package?
it is easier than use the submodule because git submodule checkout take long time, very large file

nu get restore much faster
maybe publish to you personal feed, see myget?

**Comment by mellinoe** [comment]
Yeah, it's on my list of tasks to do. I haven't done it yet since I've found submodules to be nicer to work with in this case. I can understand why others would not prefer that, though.

There is a distinct advantage to using the submodule, though. There are some `DEBUG`-only codepaths which can be very useful for identifying problematic uses of the API. These involve rather expensive checks which are not enabled in the release version of the library (or equivalently, the NuGet package version). Examples:

* Validate buffer sizes are correct after uploading. This has helped discover obscure differences in driver handling across OS's.
* Validate shader parameters have the correct names and the correct sizes (API usage / specification errors). This involves very costly shader reflection which isn't needed during regular running of an application.
* Skipping optimization in shaders and other stuff (for easier debugging). This could / should be exposed in the API, but I haven't done it so it's only exposed through the preprocessor directives.

In any case, I definitely do plan to make a nuget package and push it out to nuget.org. I'll probably do that sometime soon.

**Comment by nictaylr** [comment]
thank i much appreciate

**Comment by mellinoe** [comment]
There's a NuGet package now, built from the master branch.

https://www.nuget.org/packages/Veldrid
