### ISSUE TITLE
Having some problems with performance

### ISSUE THREAD

**Issue by BarisUckardes** [mellinoe/veldrid#318]
I was curious about **how many draw calls** my custom engine can  handle.I was expecting low results due to **im a veldrid beginner** but still im surprised by the result.

**Some info about my setup:**
- I have simple quads (4 vertex,6 indexes,4 uv coordinates)
- I draw to a render texture 1024x1024(not even my native resolution 1920x1080)
- I have **1000** draw calls per frame
- Pipelines created **for once** at the **beginning** of the engine so there is no pipeline creation per draw call
- No realtime resource creation, every resource created **before** the engine **render loop begins**
- I update only one uniform buffer and that is the MVP buffer per object.(**64 bytes**)
- My fragment shader is nothing heavy just directly outputs the color of a **single texture**
- I bind my graphicsResourceSets for **each drawcall**(They are created at the begining i just set them)
- There is no cpu bottlenecks my render loop is pretty **lightweight**(Usage is around **%2-%3** waiting for the gpu all the time)

**Results:**
1000 draw call -> 60ms (18-20FPS)
200 draw call ->  25ms(40FPS)

**200** draw call **40FPS** is insane.I mean there will be more(way more) complex shaders later such as **geometry shaders** and some **compute shaders**  **PLUS** cpu logic for the entities in the scene if i add them up i would expect nothing less then 200 ms.

I searched for a while in veldrid docs and only warning i come by is "**do not create resource||resourcesets every frame its not performant**" kind of warning.

I have a **gtx1060** its not the best gpu around but it should handle way more(or just more) batches than 1000 at 60FPS
I am aware of the nature of draw calls and why they are not performant thus we need to **batch** them together but i didnt expected these results.

**Further info:**
-When i change my render texture resolution **1024x1024** to **128x128** i reduce my frame time by **%30** (I dont understand why the **fillrate** affects that much when i use the **most basic fragment shader**)
-If i change my render loop layout a little bit and create uniform buffer and graphics pipeline **for each draw call** my frame time goes up 60ms to 100m (I expected way more than 100 ms)

If this is how i struggle with 200 batches i cant imagine when i try to add light to the scene and render the scene as a depth buffer.That would mean 200 batches more and it would result way worse than before.

**Conclusion:**
I severely think that im missing something vital about the **veldrid's graphics pipeline**.
I dont think its a Veldrid performance issue im sure im using something wrong here

I could really use some help||tip with this topic.

**Comment by mellinoe** [comment]
Performance is a complex subject, and without access to all your source code or a performance trace (CPU, GPU, or both), it's very hard to say what's happening. "Draw calls" are not a very precise measure of the amount of work being done by your application. Veldrid offers a pretty thin abstraction over the native layer, so the kinds of things you need to look for will be the same as for a native graphics application. I can offer a few suggestions on things to look into, starting from obvious / basic to more advanced:

* Is your code optimized? In other words, are you running this in Debug or Release mode? Performance numbers are not very interesting unless you are using fully optimized code.
* Which backend are you using? Some graphics APIs (OpenGL) are naturally slower than others and will perform worse.
* You say that your app is waiting for the GPU most of the time -- how did you determine that, and what does your GPU usage look like when this is running?
* What do your draw calls look like? Are you sharing vertex buffers, index buffers, shaders, pipelines, etc.? Or does each draw call have a unique set of shaders, buffers, and textures that it uses?
* How are you updating the uniform buffers for your draw calls? For large sequences of draw calls like this, you will want to use separate buffers and `GraphicsDevice.UpdateBuffer` instead of `CommandList.UpdateBuffer`.
* Are you using indexed drawing, instancing, etc.?
* Are you using a depth buffer and do you have depth testing enabled? Are you sorting your draw calls by distance, resource similarity, etc.?
* Following the above bullet, how much overdraw do you have (tools like RenderDoc can tell you this)? In other words, how much time are you spending rendering quads on top of each other that won't end up being visible?
* Are your shaders optimized? We talked earlier about a workaround to disable optimization in Veldrid.SPIRV, but this isn't the ideal way to use the library.

**Comment by BarisUckardes** [comment]
> Is your code optimized? In other words, are you running this in Debug or Release mode? Performance numbers are not very interesting unless you are using fully optimized code.

Tried using both **debug** and **release** mode but it did no noticeable performance changes

> Which backend are you using? Some graphics APIs (OpenGL) are naturally slower than others and will perform worse.

Im using **D3D11** i dont think its'a backend issue

> You say that your app is waiting for the GPU most of the time -- how did you determine that, and what does your GPU usage look like when this is running?

I take miliseconds **before** the **SumbitCommands** and one **after** its done so thats how i confirm my bottleneck is gpu.
Although my GPU device usage shows %**60** on task manager and CPU %10 i dont understand why my gpu isnt above %**90** when it takes full **55ms** to submit and present commands.

> What do your draw calls look like? Are you sharing vertex buffers, index buffers, shaders, pipelines, etc.? Or does each draw call have a unique set of shaders, buffers, and textures that it uses?

I have 1 **unique** vertex buffer,index buffer,shader set and pipeline.
So i set them **once** and **reuse** them.

> How are you updating the uniform buffers for your draw calls? For large sequences of draw calls like this, you will want to use separate buffers and GraphicsDevice.UpdateBuffer instead of CommandList.UpdateBuffer.

I update with `GraphicsDevice.UpdateBuffer` for every draw call.So there is a **1000** uniform buffer update per frame.I would normally update them when their position,rotation,scale changed but im  considering the worst case where they all moving in all times .I removed uniform buffers alltogether(both create and update,I used screen coordinates) and test it.Managed to drop 3-4 ms.(So its not a `GraphicsDevice.UpdateBuffer` bottleneck even if its poorly used) 

> Are you using indexed drawing, instancing, etc.?

I use indexed drawing.(4 vertex,6 index) per draw call

> Are you using a depth buffer and do you have depth testing enabled? Are you sorting your draw calls by distance, resource similarity, etc.?

Im using a depth buffer and i have enabled both **depth test** and **depth write**.Im not sorting my draw calls in any way.All draw calls submited via basic for loop and there is no sorting by resource i use the same resources for each draw call.

> Following the above bullet, how much overdraw do you have (tools like RenderDoc can tell you this)? In other words, how much time are you spending rendering quads on top of each other that won't end up being visible?

Without renderdoc i can say a lot.I draw my each quad at the **same position**.So every quad after the first one its an overdraw.
(But in every game isnt that the case? there are lots of overlapping triangles even with static occlusions WITH VERY COMPLEX SHADERS ?)

> Are your shaders optimized? We talked earlier about a workaround to disable optimization in Veldrid.SPIRV, but this isn't the ideal way to use the library.

Yeah that was the first thing that i checked because it gave me alot of trouble and got it solved via your help.
I checked with debug on/off it did no visible changes in terms of performance.After all i use only one texture and you is directly

My fragment shader looks like this

```
@"
 #version 450

layout(location = 0) in vec2 tex_coords;
layout(location = 0) out vec4 fragmentOutput;
                                            
layout(set = 1,binding = 0) uniform texture2D tex1;
layout(set = 1,binding = 1) uniform sampler tex1Sampler;


void main()
{
        
 fragmentOutput = texture(sampler2D(tex1,tex1Sampler),tex_coords);
}";
```
As you can see nothing even **near** the complex.

**Some further info**
If i set my quad positons offscreen i get 3ms per frame(333 FPS) even though i sumbit 1000 draw calls 1000 uniform buffer updates AND resource set updates PER FRAME.

I got really confused by this.I still refuse to beleive it's an fillrate issue 👎 

If you need further information i can share the source code

**Comment by BarisUckardes** [comment]
I have found the issue,it's not a fillrate ||depth||depth write/test issue.It seems some functionality that i couldnt predict led to uniform buffer creation for each frame and pipeline too.

So basically every frame I

created 1000 uniform buffer
updated 1000 updated buffer
created 1000 grahpics pipeline
set 1000 graphics pipeline

I fixed uniform buffer creation per frame, now  i only update it.

This dropped my frame time from 66ms to 6ms 🥇 

Although still creating 1000 graphics pipelines and set them per frame and receiving 6ms per frame is absolute crazy and honestly i didnt expect this result.

At first when i found veldrid, i thought well its c# wrapper around native backend i'll keep my expectation low in terms of raw performance but  as you mentioned
> Veldrid offers a pretty thin abstraction over the native layer 

Its safe to close this issue now.
