### ISSUE TITLE
Uploading mat4 as vertex attribute

### ISSUE THREAD

**Issue by bootzin** [mellinoe/veldrid#320]
I was following the instancing example for veldrid, and I was wondering if it would be faster to calculate the transform in CPU instead of GPU, but when I tried to implement it I realized VertexElementFormat doesn't support Matrix4, and uniforms aren't viable in this case.

Is there a reason for this not being supported? Am I always supposed to do the transform in GPU, no matter how many vertices my mesh may have?

**Comment by mellinoe** [comment]
Vertex elements can't be Matrix4x4's because it's not uniformly supported by the various graphics API's in the background, although it could perhaps be emulated to some degree if it was valuable enough. However, you still have a couple of options if you actually want to try something like this:

1. Pass the matrix separately as 4 `Vector4` attributes (1 for each row of the matrix) and then put them back together in the shader.
2. Rather than use a uniform buffer, you could use a [Structured Buffer](https://veldrid.dev/articles/shaders.html#structured-buffer), which can store a large number of matrices. You would index into this buffer using the instance ID.

**Comment by bootzin** [comment]
Alright, I'll give this a try, thx!
