### ISSUE TITLE
Input and Audio libraries for veldrid?

### ISSUE THREAD

**Issue by Shadowblitz16** [mellinoe/veldrid#322]
Is it possible to get input and audio libraries for this?
I know there is sdl2 but I think that the sdl2 methods should be ported over to a veldrid namespace

**Comment by mellinoe** [comment]
I've tried to keep most of the Veldrid libs in here focused on graphics. There are a few extra pieces in here (like Veldrid.SDL2, Veldrid.StartupUtilities, etc.), but those are intended to be basic, and not full-featured libraries on their own. For audio, I'd suggest checking out [SharpAudio](https://github.com/feliwir/SharpAudio) by @feliwir, one of the contributors here. For input, I'm curious as to what kinds of features you are looking for. There may be something out there already, or you may be able to simply get what you need from SDL2 directly.

**Comment by Shadowblitz16** [comment]
so then this is a no for supporting input and audio in veldrid?

this is one of the good things about opentk is you have most of what you need all wrapped up into a single library

**Comment by tzachshabtay** [comment]
@Shadowblitz16 veldrid does have input, here's an example of how I'm using it: https://github.com/tzachshabtay/MonoAGS/blob/veldrid/Source/Engine/AGS.Engine.Desktop/AGSInput.cs#L58

**Comment by mellinoe** [comment]
> so then this is a no for supporting input and audio in veldrid?

Audio - no plans to expand the library to cover that. It's just not my area of expertise, and I'm a big believer in modular libraries, so Veldrid is designed in a way that lets you use whichever audio library you want with it.

Input - As @tzachshabtay mentioned, Veldrid does support input, via SDL2. I don't intend on adding anything higher-level than that because, again, it's not my area of expertise and isn't a goal of the library.

**Comment by jhm-ciberman** [comment]
@mellinoe In your experience, what cross-platform audio playback library do you recommend for C#?

**Comment by mellinoe** [comment]
@jhm-ciberman Check out [SharpAudio](https://github.com/feliwir/SharpAudio) that I linked above
