### ISSUE TITLE
Y-Axis Flipped when Rendering FBO to Texture in OpenGL

### ISSUE THREAD

**Issue by geoeo** [mellinoe/veldrid#35]
When rendering a scene to a FBO color attachment and then sampling the texture the Y-Axis is flipped in opengl.

In the example the coloured quad and the cube are rendered to the quad on the right.

## Using Metal

<img width="1072" alt="metal" src="https://user-images.githubusercontent.com/1128542/35937699-56c05bc8-0c47-11e8-852e-59942c015bed.png">

## Using OpenGL

<img width="1072" alt="opengl" src="https://user-images.githubusercontent.com/1128542/35937720-6a1a4abc-0c47-11e8-9349-a4c0008ecf55.png">

Best,
Marc

**Comment by mellinoe** [comment]
Yes, this is true. Unfortunately, it's one of the few API differences that's hard to hide or paper over. Do you have a suggestion as to how this could be improved?

**Comment by geoeo** [comment]
Oh really. Thats interesting. Why does this happen with FBO's in OpenGL? 

Well, for me at least, I dont mind this behaviour as long as it is anticipated/ works across all platforms in Veldrid. 

If I could set the Y-Axis/Y write order in a texture view(or something similar) then that would already be very helpful. e.g `TextureLayout.WriteYInverted`.

I guess then the problem becomes which write order is defined to be "correct" and which one is "inverted". But I would need to know more about the specifics of the problem.

Also, I am now compensating for this in the shader. Is there a way to do this on the CPU side?

Best,
Marc

**Comment by mellinoe** [comment]
> Oh really. Thats interesting. Why does this happen with FBO's in OpenGL?

At the most basic level, it's just because of a fundamental difference in conventions between OpenGL and every other graphics API.

OpenGL texture coordinates have an origin (0, 0) at the bottom-left corner of the image. D3D and other API's have the origin at the TOP-left corner of the image. From there, you can see that the Y-axis will be flipped with all else being equal. However, you almost never actually encounter anything wrong with this, expect in one case: sampling a rendered image from a framebuffer. This is because when you upload texture data regularly (e.g. it's not the output of a render pass), then the data is placed in the correct orientation (from the bottom up). Reading from these textures will obviously be fine, because they are oriented as expected. However, the output of a framebuffer in OpenGL has the same orientation/coordinate layout as other graphics API's. This means sampling the output of a framebuffer will be "upside down" because of the difference in texture coordinate conventions.

There's two main ways you can fix this:

1. When you construct your vertex data on the CPU, you can flip the UV coordinates of your quad that you are rendering to. Instead of the "top" vertices having Y-coordinate 0, they should have Y-coordinate 1. The "bottom" vertices would have Y-coordinate 0. For a simple quad for a full-screen pass or something, this works fine.
2. In your shader, you can correct the difference by flipping the Y-coordinate. Since you already need per-API shaders, this is a pretty simple logical place to do it.

This is probably a good place to mention that there is another important difference in coordinate systems between the graphics backends: clip space coordinates. There are some articles on the internet regarding these differences, but I should put something into the docs website about these differences. In general, they are simple to solve, but the exact solution depends on the conventions you are following in your project. The relevant differences for you might be:

* Metal: Clip space Z goes from [0, 1]
* OpenGL: Clip space Z goes from [-1, 1]

If you are using the System.Numerics types, then those will give you coordinates that match the D3D conventions (which incidentally match Metal's). So you would want to correct OpenGL's clip-space Z coordinate at the end of your vertex shader by doing something like:

```GLSL
gl_Position = ... // regular computations in your shader

// Fix up clip space depth
gl_Position.z = gl_Position.z * 2.0 - gl_Position.w;
```

That will scale a [0, 1] depth into the expected [-1, 1] range for OpenGL.

Again, the exact fix will depend on what conventions you are using in your program. If your projection matrices are matching OpenGL's conventions (e.g. you're already mapping depth into the [-1, 1] range), then you would need a fix in the opposite direction for Metal, since it is expecting [0, 1].

These clip space differences aren't as critical as the texture coordinate differences. If you fail to correct OpenGL's clip space, then you will just be sacrificing 50% of your depth range unnecessarily.

I'm papering over some stuff to be (more) brief, but I hope that helps a little bit.

**Comment by geoeo** [comment]
No, that make sense. Thanks for your effort in writing this. 

Ive only used OpenGL until now, so I never ran into this issue. In that case, documenting for people like me makes the most sense. 

Best,
Marc

**Comment by mellinoe** [comment]
I've added a new article [here](https://mellinoe.github.io/veldrid-docs/articles/backend-differences.html) which I will use to document all of the backend differences that should be accounted for. Currently it contains the two cases I listed above, clip space differences and OpenGL framebuffer sampling. Feel free to re-open this if you feel there is more to discuss or if you have any related questions.
