### ISSUE TITLE
NeoDemo crash

### ISSUE THREAD

**Issue by Krakean** [mellinoe/veldrid#36]
Compiled up-to-date master, trying to run NeoDemo.dll:
https://i.imgur.com/Q4VqmIQ.png

Not sure whether it will help, but there is screenshot from Visual Studio:
https://i.imgur.com/qQUl1wd.png

**Comment by mellinoe** [comment]
Hmm, this seems to be a problem with the OBJ / MTL file parsing. There was an old bug related to different number formats from different culture settings, but that has been fixed long ago and didn't look like this.

It's sort of a shot in the dark, but perhaps your line endings got messed up when you cloned the git repo? It's possible that the OBJ/MTL files kept their Unix line endings and aren't being split up correctly. I would have guessed that a lot of other stuff would break if that were the case, though. Can you tell me how many elements are in the `atriumFile.MeshGroups` array on line 124? That might give a better idea of the problem.

Also, you're running in Release mode. Is there any better information if you run in Debug mode?

**Comment by Krakean** [comment]
@mellinoe 
Forgot about Release configuration. My bad. Here is updated screenshot:
https://i.imgur.com/vZoWzwM.png

**Comment by mellinoe** [comment]
The problem does seem to be reading Unix line endings on Windows. I just tested that myself and got the same error as you. The ObjParser class used to correctly handle this when it was using `Span<T>`, but I deleted that version because `Span<T>` wasn't working correctly at the time.

Can you try this branch? https://github.com/mellinoe/veldrid/tree/fix-obj-parsing

**Comment by Krakean** [comment]
@mellinoe Yezzz. Now it works fine. Thanks.

**Comment by mellinoe** [comment]
@Krakean Glad to hear that. I will merge that change in with the next release.
