### ISSUE TITLE
extremely slow shader compilation

### ISSUE THREAD

**Issue by mjkkirschner** [mellinoe/veldrid#361]
I'm using veldrid 4.8 along with veldrid.spirv 1.0.13 to compile a glsl shader for directX backend.

the shader is a compute shader and has a section like this:
```
uint samples = 256;
for (uint i= 0; i< samples; i++ ) {
		
    while (count < 5)
     {
             count = count + 1;
	}
}
``` 

as samples is increased from 8 to 256 - the shader compilation time goes from a few seconds to multiple minutes... 

I am using a call like this to actually load the .glsl file:
```
 var computeShader = gd.ResourceFactory.CreateFromSpirv(new ShaderDescription(
               ShaderStages.Compute,
               ReadEmbeddedAssetBytes("compute.glsl", typeof(Program).Assembly),
               "main"));
```
and I have identified this call as the slow section in my program.

my guess is loop unrolling? It seems that the directx shader compiler is invoked with optimization level3 - perhaps this has something to do with it?

just looking for direction at this moment or if this is a known issue.

### edit:
changing backend to vulkan returns compile time down to a few seconds.

**Comment by mellinoe** [comment]
Yeah, this must be triggered by some loop unrolling behavior in one of the compiler backends. Are you able to try compiling your shader on the command line, to see whether Veldrid.SPIRV specifically is the problem?

> changing backend to vulkan returns compile time down to a few seconds.

This suggests to me that the slow-ness is due to SPIRV-to-HLSL cross-compilation, rather than the GLSL-to-SPIRV compilation.
