### ISSUE TITLE
[Feature Request] Disable not needed graphics API?

### ISSUE THREAD

**Issue by Krakean** [mellinoe/veldrid#40]
@mellinoe 
Is there any way to disable graphics API that you don't need?
May be some global defines like VULKAN_ENABLE / D3D11_ENABLE ?
For example, in my project I would like to support only Win64 & OSX64, so I need only D3D11 & Metal support, thus would like to disable OGL/Vulkan (so as result to not have a dependency on Vk module)

Can you add such feature (if there is none yet), please?

**Comment by mellinoe** [comment]
There's no way to do this at the moment, but I can see why someone might want it. However, I have to be careful about adding a ton of little "feature flags" that you can switch on and off, because it's going to blow up the test matrix for Veldrid. As you found with the `VALIDATE_USAGE` flag, it's easy for things to fall out of sync and stop working, especially if I'm not using them myself. If this is added, I need to make sure it's done in the most manageable way, and with lots of tests.

**Comment by Krakean** [comment]
@mellinoe 
>As you found with the VALIDATE_USAGE flag, it's easy for things to fall out of sync and stop working
Yes, I understand it. But flags that allows you to disable unneeded graphics API seems important to me (and may be to some others who dont use all set of gfx APIs in one project), and I cant describe it as "little" feature flags :)

**Comment by mellinoe** [comment]
I describe it as "little" because each individual flag will not be very hard to add (just a few #if's and some project configuration changes), but added all together they can get very cumbersome to test. For example, it makes sense to allow every backend to be disabled (so you could get rid of D3D11 when deploying your Metal application, and vice versa), so now there's 4 extra flags, all of which can be arbitrarily combined together. Add that to `VALIDATE_USAGE`, and you've already got ~30 combinations.

Another issue is that the .NET project system really doesn't handle this kind of feature flag well. I'll need to set up a framework in the project files to streamline this.

I'd still like to do it, I just need to wrap my head around what the best approach is and how to best manage the complexity.

**Comment by Krakean** [comment]
@mellinoe 
Ok, got it. Will wait for these flags :)
You can start with Vulkan ;)

**Comment by mellinoe** [comment]
@Krakean Just to set expectations: I'm not planning on working on this in the immediate future. There are quite a few other features I am interested in adding in my limited time -- some of which are listed in the other roadmap issue. Since this request is a bit trickier and involved, it would take a lot of time away from those other features. I don't think you necessarily need to keep your project on hold for this, though. Having a bit of unused code or unused dependencies during development isn't really a big deal, especially if you know they'll go away eventually.

 If you're feeling adventurous, though, you could certainly take a stab at part of it, even if it was just for Vulkan at first. We could keep the work in a separate branch while we worked out all of the different flags.

**Comment by Krakean** [comment]
@mellinoe 
>If you're feeling adventurous

Got it, will try then to start with Vulkan :)

**Comment by Krakean** [comment]
@mellinoe 
Done - https://github.com/mellinoe/veldrid/pull/42
Works like a charm.
One thing I didn't uploaded - changed .csproj files for NeoDemo, Veldrid, Veldrid.ImGui, Veldrid.StartupUtilities, Veldrid.Tests with added "GFXAPI_VULKAN_ENABLED" define.
If you will accept this PR, I will start to make new one for Metal, then OGL & D3D11. 
And in result we will have a lot of defines, so I suppose may be you can came up with some common properties file where we can set defines that are common* for a few projects simultaneously.
So this small thing-to-do I leave to you, hopefully you're okay with it :)

* - after all, you can't compile NeoDemo with GFXAPI_VULKAN_ENABLED and Veldrid without GFXAPI_VULKAN_ENABLED

**Comment by mellinoe** [comment]
I've merged this into master now. I applied another patch on top of it because I didn't like how things were organized in the project file, so things are slightly different now:

* I've inverted the conditionals to better match the "default" state. So now, you need to define `DISABLE_D3D11_BACKEND`, `DISABLED_VULKAN_BACKEND`, etc. and these are not defined by default in the project file.
* The project file now uses well-known property names to influence these defines. If you use the default project file, you should specify `/p:DisableD3D11=true`, `DisableVulkan=true`, etc. When those properties are set, then the project file sets the appropriate define constants and removes the project references and compile items, etc.
