### ISSUE TITLE
OpenGL ES Support

### ISSUE THREAD

**Issue by generatives** [mellinoe/veldrid#45]
This evening I looked into running Veldrid on Android, using Veldrid.StartupUtilities and MonoGame's MonoGameAndroidGameView.cs as references. I noticed StartupUtilities requests OpenGL 4.0 when it is creating a context. I was wondering if Veldrid supports OpenGL ES and if so, which versions it supports. Is there a OpenGL 4.0 equivalent or otherwise compatible OpenGL ES version I should request when creating a context on Android? Thank you.

**Comment by feliwir** [comment]
Currently there is no OpenGL ES support. But there is Vulkan supported which should run on newer android hardware.

**Comment by generatives** [comment]
Ok, I will look into that instead. Thanks!

**Comment by mellinoe** [comment]
At the moment there is no integration for Android or iOS, although they could be supported by the Vulkan and Metal backends. For Vulkan, you will need to create a new kind of [VkSurfaceSource](https://github.com/mellinoe/veldrid/blob/master/src/Veldrid/Vk/VkSurfaceInfo.cs) that creates a `VkSurface` for Android. Unfortunately I don't have an Android device to test this with. It should be pretty straightforward, but I don't know much about Xamarin or MonoGame's Android classes. What you need is to fill in [this structure](https://github.com/mellinoe/vk/blob/master/src/vk/Generated/Structures.gen.cs#L1622) and then use it in the `vkCreateAndroidSurfaceKHR` function. Filling in the structure is pretty simple, because all you need is the `ANativeWindow` pointer. But, again, I'm not sure what that corresponds to in the Xamarin SDK.

If/when I get an Android device to play with (maybe there's a cheap one with Vulkan support), I will try to merge the above into library.

**Comment by mellinoe** [comment]
As another aside, when I last tried it, I found that there were multiple critical bugs in the mono runtime that prevent Veldrid from working on it, at least in the OpenGL and Metal backends. I believe they have been fixed in the very latest release (or in the next to-be-released version), but I'm uncertain if there are further bugs beyond that as I gave up out of frustration.

It's possible that those bugs aren't in the mobile mono runtimes -- I've not tested there.

**Comment by generatives** [comment]
Unfortunately I don't have an Android device that supports Vulkan so I
probably won't be pursuing this any further.

**Comment by mellinoe** [comment]
@generatives No problem. The above description will help remind me what needs to be done when I get around to this. OpenGL ES is somewhere on the roadmap, so feel free to check back in a little while and hopefully it will be implemented.

**Comment by generatives** [comment]
OpenGL ES would be great, it seems like Vulkan is not widely supported on
mobile devices. I imagine that would be a big project though.

**Comment by mellinoe** [comment]
Actually, I'm hoping that OpenGL ES will be very easy to add, because I can just start with the OpenGL backend and be 75% of the way there (hand-waving). In an older version of the library I did the same and it was very easy. But I had only ever tested that with my desktop Nvidia drivers (which do support OpenGL ES on Windows), and I don't really trust that it would have worked on Android or iOS for example.

I just need to get some kind of cheap device that I can test it on.

**Comment by mellinoe** [comment]
I bought a cheap Android device that I can test this on (and I've also got myself set up for testing on my iPhone), so I should be able to start working on this sometime soon. It's just a matter of setting aside the time at this point.

**Comment by generatives** [comment]
That's good news! I've got a Sony Xperia z5 if you need another tester. I'd
like to participate but I don't think I know enough about OpenGL ES.

**Comment by taumuon** [comment]
Hi, I'm really keen on OpenGL ES 3.1 support. I've tried OpenTK, and opengl.net, and got frustrated that either they claimed to create a 3.1 es context on the device, but wouldn't compile 3.1 version shaders, and wouldn't create a ES context on my desktop (I can't remember with which library I had which issue, I got too frustrated...)

I can test any builds on my device (an LG-G4).

Thanks!

**Comment by mellinoe** [comment]
![veldrid-gles](https://user-images.githubusercontent.com/8918977/37384798-1b34b0f4-270e-11e8-94a3-0be214a79909.png)

I've got basic OpenGL ES support up and running now, in this branch: https://github.com/mellinoe/veldrid/tree/opengles. It took almost nothing to get this working on my Windows desktop, but I have yet to try it on my Android. I fiddled around with some basic Xamarin apps to get myself familiar with how they work, so I think I understand how to integrate Veldrid now.

I've only tested the code paths that NeoDemo hits (which admittedly is fairly large), so there's probably still a fair chunk of stuff that's completely broken.

**Comment by taumuon** [comment]
hi, I got the branch, and built and tried to run the NeoDemo, and am getting an exception:
"VeldridException: Unable to compile shader code for shader [ShadowDepth-Vertex] of type VertexShader: ERROR: 0:2: '#version' :  version number '5' not supported by current context"
I'm running on an Intel 7th gen CPU (supports OpenGLES 3.2).
Thanks!

**Comment by mellinoe** [comment]
@taumuon I suppose that is to be expected on a conforming driver. The shaders it is trying to use right now are for desktop GL, which aren't the same as shaders for OpenGL ES. Apparently my Nvidia drivers are able to handle it, even though they shouldn't.

I've finally figured out how to hook up an OpenGL ES context on Android, so I'm able to start running through code there. I've already hit a few things that my Nvidia drivers allow but aren't legal.

**Comment by mellinoe** [comment]
@taumuon I updated ShaderGen so it now generates valid GLES shaders. I know there are definitely more issues, especially with something as large as NeoDemo, but the shaders should at least be correct now. Feel free to pull down the latest and try it out.

Next, I'm going to start refactoring the projects in [Veldrid-Samples](https://github.com/mellinoe/veldrid-samples) so that they can easily be run on Android (and iOS, potentially). Then, I'll work through each one and see what issues I hit.

**Comment by mellinoe** [comment]
Quite a bit is now working, but that's only with a lot of hacks. I'm going to put a hold on further work until Xamarin is in a more manageable state. Hopefully then I can remove my hacks and feel a little bit better about merging in the code.

**Comment by tzachshabtay** [comment]
Can you share the list of xamarin bugs you saw?

**Comment by mellinoe** [comment]
This is the main one: https://github.com/xamarin/xamarin-android/issues/1196. It's the most frustrating one and I've tried several things to fix it. I'm trying to work on a couple dozen projects (all of the sample projects), so it's pretty frustrating to have to apply hacks to every new project I add. The last comment says it should be fixed soon, though. Hopefully there's a new SDK I can try out soon that fixes it.

[This bug](https://github.com/mono/mono/issues/6411) is also present, although it has been fixed in mainline mono. I'm not sure when that gets integrated with the mobile platforms, but I would rather not merge in the workarounds in the meantime (I've replaced all of the Vector2/3's that are uploaded to the GPU with individual float fields).

There is a similar issue with Xamarin.iOS to the first one, but I'm not sure it's the same as 1196. I've been focusing on Android so I didn't look into it closely. The error wasn't exactly the same, but it was also related to missing assemblies/references.

I hit another issue with the mono runtime that I didn't look into closely. I'll go back and file a bug because I didn't see anything about it when I looked. Essentially trying to load [DisposeCollectorResourceFactory](https://github.com/mellinoe/veldrid/blob/master/src/Veldrid.Utilities/DisposeCollectorResourceFactory.cs) was failing because of a "missing vtable" or somesuch. The error message made me think it might have something to do with the other hacks I was using, because I ended up referencing several versions of nuget packages in order to get all of the projects building at once. It could be unrelated to any of that, though. [This](https://github.com/mellinoe/veldrid-samples/blob/restructure/src/SampleBase.Android/AndroidApplicationWindow.cs#L10-L11) is how I'm working around it.

**Comment by taumuon** [comment]
@mellinoe I got around to trying the latest OpenGLES changes, they work great on my laptop :) Thanks for the xamarin update, I'll keep an eye out for when it's ready...

**Comment by mellinoe** [comment]
@taumuon Glad to hear it. Did you run NeoDemo, or something else?

**Comment by taumuon** [comment]
it was the NeoDemo. I've got some other code I want to try porting over when I find time...

**Comment by mellinoe** [comment]
@taumuon Sounds good. NeoDemo covers a lot of stuff so it's a good sign that it works :).

I've also enabled all of the tests for OpenGL ES and they pass for me. I need to set up some way to run all of the tests on my Android device, but that will be a bit of a pain (gotta figure out how to use the Xunit console runner on it).

**Comment by mellinoe** [comment]
I'm getting pretty close to merging in the OpenGL ES support to master. I'm planning on doing a 4.2.0-beta version before going stable, as there's quite a few changes going in. For the time being everything is still in the [opengles](https://github.com/mellinoe/veldrid/tree/opengles) branch.

**Comment by mellinoe** [comment]
OpenGL ES support is now merged in to master, along with several supporting changes. I'm planning to release at least one beta version before going stable with this, and I'll prepare a more detailed description of all the additions, but here's a basic overview:

* `GraphicsBackend.OpenGLES` has been added.
* You can use the existing `GraphicsDevice.CreateOpenGL` function with a pre-made GLES context to create an OpenGLES GraphicsDevice. This assumes you've created the GLES context outside of Veldrid, same as how the current OpenGL support works.
* There is also a `GraphicsDevice.CreateOpenGLES` overload, which takes a `SwapchainDescription` parameter. If you pass this a description with a SwapchainSource created from an Android Surface or an iOS UIView, then it will create an OpenGLES context for you, configured to render into the given surface/view. In the future, I'd like to allow Veldrid to create GL contexts itself (on desktop platforms), but it's a lot of annoying work.
* There is now a GraphicsDeviceFeatures object, which enumerates which specific features a particular GraphicsDevice supports.

**Comment by mellinoe** [comment]
4.2.0-beta1 is out now, and it includes OpenGL ES support. The sample projects in https://github.com/mellinoe/veldrid-samples/ have also been updated to show Android and iOS usage.

**Comment by mellinoe** [comment]
4.2.0 is stable now, and includes OpenGL ES support
