### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by ShalokShalom** [mellinoe/veldrid#479]
The last release here on Github is from 2018

Is this intended? 
Do you bet on NuGet only?

Just curious:)

**Comment by mellinoe** [comment]
I haven't really been using the GitHub "Releases" tab consistently. There are much newer versions available on NuGet which are generated from [tagged commits](https://github.com/mellinoe/veldrid/tags). That said, a full, stable release is a bit overdue as the last 2 releases have been beta versions.

**Comment by ShalokShalom** [comment]
I just think that some bots, lists and so on (Wikipedia eventually) track the Github releases. 

And from that perspective, the project is dead.

**Comment by mellinoe** [comment]
For .NET projects, I think the standard is to simply look at NuGet releases. That said, since the release process is now mostly automated via GH actions, we can just add a step that creates a new Release, e.g. like [this](https://github.com/mellinoe/ImGui.NET-nativebuild/blob/master/.github/workflows/build.yml#L142-L152). I'll try to get that going for the next one.
