### ISSUE TITLE
Implement API calls for mipmapping.

### ISSUE THREAD

**Issue by geoeo** [mellinoe/veldrid#61]
As per the mention on gitter, I thought it would be worthwhile making an official request for this.

Having direct access to mipmapping is not only beneficial for graphics applications but also for GPGPU apps. E.g. calculating image pyramids. 

The API calls are as follows:
OpenGL: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGenerateMipmap.xhtml
Metal: https://developer.apple.com/documentation/metal/mtlblitcommandencoder/1400748-generatemipmapsfortexture
DirectX: https://msdn.microsoft.com/en-us/library/windows/desktop/bb206251(v=vs.85).aspx (? - not sure since it DirectX 9)
Vulkan : No direct mipmapping here. Would have to use a compute shader chain, as stated in the gitter chat.

**Comment by mellinoe** [comment]
D3D11 supports it, at least for a subset of formats:
https://msdn.microsoft.com/en-us/library/windows/desktop/ff476426(v=vs.85).aspx

Vulkan can also do it using image blits, which would be easier to implement than a compute shader: https://github.com/SaschaWillems/Vulkan/tree/master/examples/texturemipmapgen

I think it could be a worthwhile addition, but it'd be a decent amount of work, and the proper interface would need to be designed.

**Comment by geoeo** [comment]
> I think it could be a worthwhile addition
Thats great to hear!

> but it'd be a decent amount of work, and the proper interface would need to be designed.

Yes, that is understandable. It shouldn't be hacked in. What are the major refactors that have to take place?

**Comment by mellinoe** [comment]
I don't think anything needs to be refactored, but I'm not sure what exactly the API should look like. I suppose what makes the most sense is this:

```C#
public class CommandList
{
    public void GenerateMipmaps(Texture texture);
{
```

To use it, you would need to create a Texture with multiple MipLevels but only fill in the first one with data. After GenerateMipmaps was called, the rest would be filled in.

There might need to be some sort of capability API to let you know if the Texture can actually be used, since D3D11 doesn't support all formats.

It would need to be clear that the reduction filter being used is implementation-defined (most of the doc pages say this somewhere), so we don't need to guarantee anything about what the mipmaps look like in the end.

**Comment by geoeo** [comment]
> There might need to be some sort of capability API to let you know if the Texture can actually be used, since D3D11 doesn't support all formats.

If it can be queried from the driver that would be great. But I dont think you should have to maintain possible changing lists of supported formats/devices. It would be one of those "at your own discretion" things.

**Comment by mellinoe** [comment]
This turned out to be way simpler than I was expecting. I implemented it in this branch: https://github.com/mellinoe/veldrid/commits/generate-mipmaps

Most backends are trivial, except for Vulkan, which I'm sure still has some bugs in it. I need to add some test cases and make sure everything works as expected before merging this back into master.

**Comment by geoeo** [comment]
> On the other hand, this method is only really intended to be used to auto-generate mipmaps for rendered scenes, so the required usage flags reflect that.

Is it possible to forego this limitation in the future? One use case I was thinking about is GPGPU programming and using mip maps without a render taget.

**Comment by geoeo** [comment]
Yeah that sounds good. I understand that this feature is not ideal for all backends as only newer apis support commandlist without render targets. Thanks for this

**Comment by mellinoe** [comment]
I ended up taking the `TextureUsage.GenerateMipmaps` approach -- it's merged into master now.
