### ISSUE TITLE
[Feature Request] OpenGL(ES) Multiple glContext

### ISSUE THREAD

**Issue by Sorrowful-free** [mellinoe/veldrid#81]
Multiple glContext for realy multythreaded Api, that is, the background context for working with resources and in the main context for rendering, if it possible

**Comment by mellinoe** [comment]
From what I have read of multiple GL contexts, this will not be worth it. Apparently, it's feature that is often neglected by drivers, with bad performance and unpredictable behavior. The OpenGL backend is already the most complicated backend, and the performance is not significantly worse than others, so my gut feeling is that it really won't be worth it. I think there some low-hanging fruit that could have a much better impact on performance while being less expensive.

It would involve managing our own creation and deletion of OpenGL contexts, which Veldrid currently only does for Android and iOS. I would like to add support for doing that automatically on Windows, macOS and Linux, but primarily to be able to support multiple Swapchains on OpenGL (currently doesn't work), rather than to use multiple GL contexts for background processing.

**Comment by Sorrowful-free** [comment]
Thanks for the quick response, in this case you can make it possible to use the scheduler instead of the execution queue in the opengl stream, so that the execution time of the operations does not exceed a certain period. For example: the time for the drawing operation was spent 6ms and the remaining 10 ms to spend on other less priority operations such as working with resources not used in the current frame?

**Comment by Sorrowful-free** [comment]
Oh, sorry, I understanded, if we need make schedule, we call drawind operation and then call WaitForIdle and then work with resources.
