### ISSUE TITLE
Is UWP XAML interop possible?

### ISSUE THREAD

**Issue by JimSEOW** [mellinoe/veldrid#9]
Is there a plan to support UWP XAML interop ?

**Comment by mellinoe** [comment]
Yes, it is possible, although I haven't tested it in a while. You just need to construct a D3DRenderContext using [this constructor](https://github.com/mellinoe/veldrid/blob/master/src/Veldrid/Graphics/Direct3D/D3DRenderContext.cs#L59), after you've created a D3D11 device and swapchain in your UWP code.

**Comment by JimSEOW** [comment]
I see that you have been pushing the limits of cross platform graphics technology (e.g. OpenTK).

I see the need for[ democratizing 3D creation/sharing](https://github.com/Microsoft/WindowsTemplateStudio/issues/561) through the emerging Remix 3D platform.

One approach will be starting sharing [3D templates ](https://github.com/Microsoft/WindowsTemplateStudio)INSTEAD of 3D engine demo samples dispersed among the ocean of github projects.

==> We need to LOWER the expectation of USERS that it is a full proof/flawless tempalte. IT is not easy to do what you are doing. We need to encourage other developers to join in the effort to sort out challenges associated with providing C# 3D templates based on XAML interOp. 

Ideally, C# 3D templates with XAML InterOp for SharpDX, Open ES (Angle), perhaps the emerging OpenTK (through .Net standard 2.0 for UWP and XAML standard) and Vulkan.

==> Veldrid, is VERY impressive! having the options of backend OpenGL/Open ES (Angle)/DirectX/Vulkan.

==> Hope you could squeeze a bit of your time experimenting with XAML interlope. 

==> For .NET C# communities, we lack critical mass of effort in addressing XAML interOp. Most of the examples are in C++/CX. Porting those examples to C# is not as straight forwards as most think.

**Comment by mellinoe** [comment]
Thanks for the ideas, I'll let you know if I have any time to invest into bringing the UWP demo back online. Having a library of templates is a bit outside the scope of this library, because this is just a low-level graphics abstraction layer. How it is integrated into your application can vary. In the end, the UWP integration code is extremely tiny -- a couple dozen lines of code on top of a basic UWP template.

The reason I got rid of the UWP code was because it was a bit harder to maintain -- I couldn't build or test it outside of Windows, and I often work on Linux. If I bring it back, it will be very basic.

One thing that I have considered is adding [dotnet new templates](https://github.com/dotnet/templating), so that you can run `dotnet new veldrid` or something like that. I probably wouldn't use them myself, but it could be an easy way to get started with the library.

As for Remix 3D: I'm not very familiar with it, but it looks like you can export regular model files from it. You can load those model files into your C# program as normal and use them with Veldrid.

**Comment by JimSEOW** [comment]
@mellinoe Sorry to come here to get your attention.

With your OpenTKCore, I am getting closer to bring OpenTK to UWP

I identify that I need 3 components to do that
(a) Use OpenTKCore for .NET Core 2.0
(b) Use System.Drawing for .Net Core 2.0
(c) Replace  **WinForm** based GLControl to **UWP** UserControl based GLControl _through the_ **WPF** UserControl based GLControl

Do you have plan to bring OpenTK ns2.0 branch further by making the GLControl at least supporting WPF UserControl so other could bring that to UWP Usercontrol?

U could follow the discussion [here](https://github.com/l3m/wpf-gles/issues/1).
