### ISSUE TITLE
Problems with shader uniform

### ISSUE THREAD

**Issue by taumuon** [mellinoe/veldrid#95]
Hi,

I've ported some OpenGL code I had over to Veldrid - it's a great library! (demo code at https://github.com/taumuon/VeldridRayCastPickingDemo) , but had some weird behaviour with one of the shader uniforms.

The main shader, ColorShader, has a uniform, DirectionalLightUniform, but if I try to use the ambient and diffuse fields from that uniform nothing is drawn (instead, the ambient and diffuse values are hardcoded in the fragment shader). Also, I had problems with the ShadowMatrix - it works if it's the first field in the DirectionalLight struct, but drawing is corrupt if it's moved to the last field.

I think it's related, but I had issues with the size of the directional light buffer size to set in the BufferDescription - it feels related. Can you see what's wrong with my code, and are there any guidelines on the structs to use in the shaders (padding/alignment?)

Thanks,
gary

**Comment by mellinoe** [comment]
> I've ported some OpenGL code I had over to Veldrid - it's a great library!

Thanks!

I ran your program under RenderDoc to figure out what the problem was.

![image](https://user-images.githubusercontent.com/8918977/42346737-762d595e-8058-11e8-8dfc-5582a3ab5f69.png)

The frame capture indicates that the `DirectionalLightBuffer` resource isn't being bound at all in the fragment shader, so blank data is being read back. The root cause is this:

`new ResourceLayoutElementDescription("DirectionalLight", ResourceKind.UniformBuffer, ShaderStages.Vertex),`

This line indicates that the resource only applies to the Vertex stage. You can change it to:

`new ResourceLayoutElementDescription("DirectionalLight", ResourceKind.UniformBuffer, ShaderStages.Vertex | ShaderStages.Fragment),`

and it should fix that problem. Let me know if you hit any other snags, I'm happy to help.

**Comment by taumuon** [comment]
Perfect, that worked :) Thanks for your help!
